### ISSUE TITLE
Requesting the following addresses to be dumped

### ISSUE THREAD

**Issue by Tioncheat** [astacodes/Roblox-Address-API#1]
RawTaskScheduler
GetGlobalStateForInstance
DecryptLuaState
LuaO_NilObject
LuaH_DummyNode
KTable
GetProperty
JobStart
JobEnd

**Comment by astacodes** [comment]
The fact that you posted this suggests a lot. GetGlobalStateForInstance is already in here as "GetGlobalState", DecryptLuaState is also here as "DecryptGlobalState". 

NilObject and Dummynode are extremely easy to obtain.

I COULD add these but I will not as you are clearly attempting to update Ballistic to probably skid it

**Comment by Tioncheat** [comment]
> The fact that you posted this suggests a lot. GetGlobalStateForInstance is already in here as "GetGlobalState", DecryptLuaState is also here as "DecryptGlobalState".
> 
> NilObject and Dummynode are extremely easy to obtain.
> 
> I COULD add these but I will not as you are clearly attempting to update Ballistic to probably skid it

okay? Im using Ballistic for personal use. Im not someone who claim I made it myself.

**Comment by efidemon69** [comment]
Do not add those, i don't want ballistic skids to use them
